### PR TITLE
Searching and Debugging Portal Source in IDE

### PR DESCRIPTION
**Pull request by codyhoag**
Hey Greg; can you review these tutorials on 

- [Searching Liferay Portal Source in Liferay IDE](https://github.com/codyhoag/liferay-docs/blob/MIGRATION-new-searching-code-ide/develop/tutorials/articles/100-tooling/02-liferay-ide/12-searching-liferay-portal-source-in-liferay-ide.markdown)
- [Debugging Liferay Portal Source in Liferay IDE](https://github.com/codyhoag/liferay-docs/blob/MIGRATION-new-searching-code-ide/develop/tutorials/articles/100-tooling/02-liferay-ide/13-debugging-liferay-portal-source-in-liferay-ide.markdown)

Thanks!

### CODE REVIEW

**Comment by gamerson** [comment]
hey cody I will try to get to this tomorrow.

**Comment by codyhoag** [comment]
@gamerson this still needs an SME review too. I've updated these articles to now reference the Target Platform docs I just drafted up. ✔️

**Comment by codyhoag** [comment]
@gamerson Do you have time to review these tutorials this week?

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-docs/pull/17. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by gamerson — APPROVED** [review]
LGTM! 👍

**Comment by codyhoag** [comment]
Awesome! Thanks, Greg! 🎉

**Pull request closed without merging**
